# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-type: all

  - package-ecosystem: 'npm'
    directory: '/packages/core'
    versioning-strategy: auto
    schedule:
      interval: 'daily'
    ignore:
      - dependency-type: development

  - package-ecosystem: 'npm'
    directory: '/packages/create'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-type: development
