# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: checkout
        run: |
          git config --global user.name '@logrythmik'
          git config --global user.email 'logrythmik@users.noreply.github.com'

      - name: setup-npm
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
      - run: npm whoami
      - name: build
        run: yarn install && yarn build
       
      - name: publish
        run: lerna publish patch --yes --no-verify-access
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
